version: '3.2'

services:

  karmabot:
    container_name: karmabot
    restart: always
    image: bomzheg/karmabot
    volumes:
      - type: "bind"
        source: "./config"
        target: "/config"
        read_only: true
    env_file: config/.env
    entrypoint: [ "python3", "-m", "app", "-p" ]
    networks:
      - reverse-proxy
      - db

  db:
    image: "postgres:16.1-alpine"
    restart: unless-stopped
    ports:
      - "127.0.0.1:15432:5432"
    networks:
      - db
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres.data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5



networks:
  db:
  reverse-proxy:
    external:
      name: nginx-reverse-proxy

volumes:
  postgres.data:
