name: Lint

on: [workflow_call, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v39
      with:
        # file list is taken from https://docs.astral.sh/ruff/settings/#include
        files: |
          *.py
          *.pyi
          **/pyproject.toml

    - name: Ruff
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: ruff check --config=pyproject.toml --diff --output-format=github ${{ steps.changed-files.outputs.all_changed_files }}
