name: Lint

on: [workflow_call, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v39
      with:
        files_yaml: |
          ruff:
            - *.py
            - *.pyi
            - **/pyproject.toml
          black:
            - *

    - name: Ruff
      if: steps.verify-changed-files.outputs.ruff_any_changed == 'true'
      run: ruff check --config=pyproject.toml --show-fixes --output-format=github ${{ steps.changed-files.outputs.ruff_all_changed_files }}

    - name: Black
      id: black
      if: steps.verify-changed-files.outputs.black_any_changed == 'true'
      run: black --config=pyproject.toml --check --verbose ${{ steps.changed-files.outputs.black_all_changed_files }}
