name: Lint

on: [workflow_call, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'requirements*.txt'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black isort

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v39
      with:
        files: |
          *.py
          *.pyi

    - name: Ruff
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: ruff check --config=pyproject.toml --show-fixes --output-format=github ${{ steps.changed-files.outputs.all_changed_files }}

    - name: Black
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: black --config=pyproject.toml --check --diff --verbose ${{ steps.changed-files.outputs.all_changed_files }}

    - name: Isort
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: isort --check --diff --profile=black ${{ steps.changed-files.outputs.all_changed_files }}
